USE CocoaLand_DB;
GO

CREATE USER Ahmed404 FOR LOGIN Ahmed404;
GO
ALTER AUTHORIZATION ON DATABASE::CocoaLand_DB TO Ahmed404;
GO
ALTER ROLE db_owner ADD MEMBER Ahmed404;
GO
ALTER LOGIN Ahmed404
WITH DEFAULT_DATABASE = CocoaLand_DB;
GO